<a href="https://colab.research.google.com/github/Jose-guerra2002/etl-data-pipeline/blob/main/etl_polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/polizas.csv

In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/polizas.csv"
df = pd.read_csv(url)
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [3]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [6]:
# Estandariza nombres de columnas (minúsculas y sin espacios extra)
def normalizar_columnas(df):
    df = df.copy()
    df.columns = df.columns.str.strip().str.lower()

    print("Columnas:")
    print(df.columns.tolist())

    return df


df = normalizar_columnas(df)

Columnas:
['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor', 'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision', 'monto_asegurado']

In [11]:
# Separa datos usando nombres reales de columnas
def separar_datos(df):
    print("Columnas disponibles:", df.columns.tolist())

    # Ajusta estos nombres según tu CSV
    validos = df.dropna(subset=['id_poliza', 'monto_asegurado']).copy()
    rechazados = df[df[['id_poliza', 'monto_asegurado']].isnull().any(axis=1)].copy()

    print(f"Válidos: {validos.shape[0]}")
    print(f"Rechazados: {rechazados.shape[0]}")

    return validos, rechazados


valid_df, rejected_df = separar_datos(df)

Columnas disponibles: ['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor', 'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision', 'monto_asegurado']
Válidos: 21787
Rechazados: 3363

In [12]:
# Asigna motivo de rechazo según campos obligatorios faltantes
def motivo_rechazo(df):
    rechazados = df[df[['id_poliza', 'monto_asegurado']].isnull().any(axis=1)].copy()

    rechazados['motivo'] = rechazados.apply(
        lambda x: 'Falta id_poliza' if pd.isnull(x['id_poliza'])
        else 'Falta monto_asegurado',
        axis=1
    )

    print("Rechazados con motivo:")
    display(rechazados.head())
    print(rechazados.shape)

    return rechazados


rechazados_pol = motivo_rechazo(df)

Rechazados con motivo:

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado,motivo
20,21,2026-01-13,179,34,2,9,"1,709.14","1,963.14",NaN,Falta monto_asegurado
28,29,NaN,1101,7,8,12,NaN,54.06,NaN,Falta monto_asegurado
31,32,2025/07/28,388,22,6,4,822.52,-,NaN,Falta monto_asegurado
34,35,19/01/2025,1139,79,1,3,"1,847.73",191.44,NaN,Falta monto_asegurado
63,64,20-07-2025,1081,75,8,1,"109,72",17.48,NaN,Falta monto_asegurado

(3363, 10)

In [16]:
validos_pol, rechazados_pol = separar_polizas(df)

Registros válidos: 21787
Registros rechazados: 3363

In [17]:
exportar_polizas(validos_pol, rechazados_pol)

OK ✅ 21787 válidos | 3363 rechazados

In [19]:
# Ejecuta separación y exportación en un solo flujo
def procesar_y_exportar(df):
    filtro = df['id_poliza'].notna() & df['monto_asegurado'].notna()

    validos = df.loc[filtro].copy()
    rechazados = df.loc[~filtro].copy()

    validos.to_csv("polizas_curated.csv", index=False)
    rechazados.to_csv("polizas_rejects.csv", index=False)

    print(f"OK {validos.shape[0]} válidos | {rechazados.shape[0]} rechazados")

    return validos, rechazados


validos_pol, rechazados_pol = procesar_y_exportar(df)

OK 21787 válidos | 3363 rechazados

In [20]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 69.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [21]:
from sqlalchemy import create_engine
import pandas as pd

In [22]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [23]:
engine = create_engine(database_url)

In [24]:
test = pd.read_sql("SELECT 1", engine)

In [25]:
print(test)

   ?column?
0         1

In [27]:
# 1. datos válidos de pólizas en la tabla
valid_df.to_sql(
    'polizas_curated',
    engine,
    if_exists='replace',
    index=False
)

787

In [28]:
# 2 datos rechazados de pólizas en la tabla
valid_df.to_sql(
    'polizas_rejects',
    engine,
    if_exists='replace',
    index=False
)

787

In [29]:

# Validar la carga de Pólizas en PostgreSQL [cite: 120-124]
pd.read_sql(
    "SELECT * FROM polizas_curated LIMIT 10",
    engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,None,184,42,15,2,"829,53",None,139253.11
1,2,2026/02/16,2408,35,11,12,None,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75
5,6,05-02-25,1295,17,1,1,943.49,None,71968.43
6,7,02-09-25,1254,25,11,4,1400.82,188.40,258202.93
7,8,2026-01-11,887,77,3,8,1670.56,258.75,-
8,9,2025-02-28,1670,66,8,12,None,"131,85",125804.84
9,10,2026/01/24,2281,69,13,3,791.38,"67,44",20710.00

In [30]:
# Copia y normaliza nombres de columnas
def preparar_polizas(df):
    pol = df.copy()
    pol.columns = pol.columns.str.strip().str.lower()
    return pol

polizas = preparar_polizas(df)

In [31]:
# Convierte fechas a formato estándar (YYYY-MM-DD)
def limpiar_fechas(df):
    df = df.copy()
    df['fecha_emision'] = pd.to_datetime(df['fecha_emision'], errors='coerce')
    return df

polizas = limpiar_fechas(polizas)

In [32]:
# Limpia y convierte monto asegurado a numérico
def limpiar_montos(df):
    df = df.copy()
    df['monto_asegurado'] = (
        df['monto_asegurado']
        .astype(str)
        .str.replace(',', '', regex=False)
    )
    df['monto_asegurado'] = pd.to_numeric(df['monto_asegurado'], errors='coerce')
    return df

polizas = limpiar_montos(polizas)

In [33]:
# Limpia columna prima si existe
def limpiar_prima(df):
    df = df.copy()
    if 'prima' in df.columns:
        df['prima'] = df['prima'].astype(str).str.replace(',', '', regex=False)
        df['prima'] = pd.to_numeric(df['prima'], errors='coerce')
    return df

polizas = limpiar_prima(polizas)

In [34]:
# Separa pólizas válidas y rechazadas según campos clave
def separar_polizas(df):
    filtro = (
        df['id_poliza'].notna() &
        df['monto_asegurado'].notna() &
        df['fecha_emision'].notna()
    )

    validos = df.loc[filtro].copy()
    rechazados = df.loc[~filtro].copy()

    return validos, rechazados

validos_pol, rechazados_pol = separar_polizas(polizas)

In [35]:
# Genera motivo de rechazo por campos inválidos
def asignar_motivo(df):
    def motivo(row):
        motivos = []
        if pd.isna(row['id_poliza']): motivos.append("id_poliza_vacio")
        if pd.isna(row['monto_asegurado']): motivos.append("monto_asegurado_error")
        if pd.isna(row['fecha_emision']): motivos.append("fecha_invalida")
        return ",".join(motivos)

    df = df.copy()
    df['motivo_rechazo'] = df.apply(motivo, axis=1)
    return df

rechazados_pol = asignar_motivo(rechazados_pol)

In [36]:
# Carga datos a PostgreSQL
def cargar_bd(v, r, engine):
    v.to_sql('polizas_curated', engine, if_exists='replace', index=False)
    r.to_sql('polizas_rejects', engine, if_exists='replace', index=False)

cargar_bd(validos_pol, rechazados_pol, engine)