In [ ]:
https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/corredores.csv

In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/corredores.csv"
df = pd.read_csv(url)
df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [3]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [4]:
def limpiar_datos(df):
    df = df.copy()

    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object'):
        df[col] = df[col].astype(str).str.strip()

    print("DataFrame limpio:")
    display(df.head())
    print(df.info())

    return df


cleaned_df = limpiar_datos(df)

DataFrame limpio:

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5      Ana Gómez Rojas          nan  Senior                4.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               80 non-null     object
 3   nivel              80 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB
None

In [7]:
corredores = df.copy()

# Normalizar nombres de columnas
corredores.columns = corredores.columns.str.strip().str.lower()

In [8]:
def limpiar_espacios(df):
    df = df.copy()

    cols = df.select_dtypes(include='object').columns
    df[cols] = df[cols].apply(lambda x: x.str.strip())

    print("Espacios limpiados:")
    display(df.head())

    return df


cleaned_df = limpiar_espacios(df)

Espacios limpiados:

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                8.0
4            5      Ana Gómez Rojas          NaN  Senior                4.0

In [9]:
def filtrar_validos(df):
    validos = df.dropna(subset=['nombre', 'zona']).copy()

    print("Datos válidos (nombre y zona completos):")
    display(validos.head())
    print(f"Shape: {validos.shape}")

    return validos


valid_df = filtrar_validos(df)

Datos válidos (nombre y zona completos):

   id_corredor                 nombre         zona    nivel  anios_experiencia
0            1      José López Flores  Paracentral      Mid                4.0
1            2      José Ortiz García     Centro     Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                 6.0
5            6  Sofía Reyes Hernández    Occidente    Elite                3.0
6            7   Pedro Vásquez Torres        Costa      NaN                1.0

Shape: (63, 5)

In [10]:
def identificar_rechazo(df):
    rechazados = df[df[['nombre', 'zona']].isnull().any(axis=1)].copy()

    rechazados['motivo_rechazo'] = rechazados.apply(
        lambda x: 'Falta nombre' if pd.isnull(x['nombre'])
        else 'Falta zona' if pd.isnull(x['zona'])
        else 'Otro',
        axis=1
    )

    print("Datos rechazados con motivo:")
    display(rechazados.head())
    print(f"Shape: {rechazados.shape}")

    return rechazados


rejected_df = identificar_rechazo(df)

Datos rechazados con motivo:

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
3,4,Fernanda Rojas Cruz,NaN,SENIOR,8.0,Falta zona
4,5,Ana Gómez Rojas,NaN,Senior,4.0,Falta zona
10,11,José Morales Flores,NaN,junior,NaN,Falta zona
11,12,Pedro Gómez Vásquez,NaN,Mid,21.0,Falta zona
16,17,Jorge Reyes Ramírez,NaN,Elite,20.0,Falta zona

Shape: (17, 6)

In [11]:
def exportar_corredores(validos, rechazados):
    validos.to_csv("corredores_validos.csv", index=False)
    rechazados.to_csv("corredores_rechazados.csv", index=False)

    print("Archivos exportados:")
    print("- corredores_validos.csv")
    print("- corredores_rechazados.csv")


exportar_corredores(valid_df, rejected_df)

Archivos exportados:
- corredores_validos.csv
- corredores_rechazados.csv

In [12]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 37.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [19]:
from sqlalchemy import create_engine
import pandas as pd

In [20]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [21]:
engine = create_engine(database_url)

In [22]:
test = pd.read_sql("SELECT 1", engine)

In [23]:
print(test)

   ?column?
0         1

In [24]:
# 1. Subir las corredores Válidas
valid_df.to_sql(
    'corredores_rechazados',
    engine,
    if_exists='replace',
    index=False
)

63

In [25]:
# 1. Subir las corredores Válidas
valid_df.to_sql(
    'corredores_validos',
    engine,
    if_exists='replace',
    index=False
)

63

In [26]:
# Validar la carga de los corredores
pd.read_sql(
    "SELECT * FROM corredores_validos LIMIT 10",
    engine
)

   id_corredor                 nombre         zona    nivel  anios_experiencia
0            1      José López Flores  Paracentral      Mid                4.0
1            2      José Ortiz García     Centro     Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                 6.0
3            6  Sofía Reyes Hernández    Occidente    Elite                3.0
4            7   Pedro Vásquez Torres        Costa     None                1.0
5            8  Paula Ortiz Hernández     Centro     Junior               17.0
6            9  Carlos Torres Vásquez  Paracentral   junior                2.0
7           10     Juan Cruz Castillo    Occidente     None                7.0
8           13  Valeria García Torres      Oriente  SENIOR                23.0
9           14     Diego Gómez Chávez     Centro     Senior               20.0