In [ ]:
https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/aseguradoras.csv

In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline/refs/heads/main/datos/raw/aseguradoras.csv"
df = pd.read_csv(url)
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [3]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [4]:
def limpiar_dataframe(df):
    df_limpio = (
        df.copy()
        .rename(columns=lambda c: c.strip().lower())
    )

    # Limpiar espacios en columnas tipo texto
    columnas_texto = df_limpio.select_dtypes(include='object').columns
    df_limpio[columnas_texto] = df_limpio[columnas_texto].apply(
        lambda x: x.astype(str).str.strip()
    )

    # Correcciones específicas
    df_limpio['pais'] = df_limpio['pais'].replace({'ElSalvador': 'El Salvador'})
    df_limpio['rating_riesgo'] = df_limpio['rating_riesgo'].replace({'B': 'Bajo'})

    # Manejo de valores nulos
    df_limpio['pais'].fillna(df_limpio['pais'].mode()[0], inplace=True)
    df_limpio['rating_riesgo'].fillna('Desconocido', inplace=True)

    # Eliminar duplicados
    df_limpio = df_limpio.drop_duplicates()

    return df_limpio


# Ejecutar limpieza
cleaned_df = limpiar_dataframe(df)

# Mostrar resultados
print("DataFrame cleaned. Here is the info:")
cleaned_df.info()

print("\nNull values after cleaning:")
print(cleaned_df.isnull().sum())

print("\nFirst 5 rows of the cleaned DataFrame:")
display(cleaned_df.head())

DataFrame cleaned. Here is the info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            15 non-null     object
 3   rating_riesgo   15 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

Null values after cleaning:
id_aseguradora    0
nombre            0
pais              0
rating_riesgo     0
dtype: int64

First 5 rows of the cleaned DataFrame:

/tmp/ipykernel_188/1932265586.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_limpio['pais'].fillna(df_limpio['pais'].mode()[0], inplace=True)
/tmp/ipykernel_188/1932265586.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_limpio['rating_riesgo'].fillna('Desconocido', inplace=True)

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           nan
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5  El Salvador          Bajo

In [7]:
def separar_datos(df):
    validos = df[df['rating_riesgo'] != 'Desconocido'].copy()
    rechazados = df[df['rating_riesgo'] == 'Desconocido'].copy()

    print("Datos Válidos:")
    display(validos.head())
    print(f"Shape: {validos.shape}\n")

    print("Datos Rechazados:")
    display(rechazados.head())
    print(f"Shape: {rechazados.shape}")

    return validos, rechazados


valid_df, rejected_df = separar_datos(cleaned_df)

Datos Válidos:

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           nan
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5  El Salvador          Bajo

Shape: (15, 4)

Datos Rechazados:

Empty DataFrame
Columns: [id_aseguradora, nombre, pais, rating_riesgo]
Index: []

Shape: (0, 4)

In [8]:
def identificar_rechazo(df):
    rechazados = df[df['rating_riesgo'] == 'Desconocido'].copy()

    rechazados['motivo_rechazo'] = 'Rating desconocido'

    print("Datos Rechazados con motivo:")
    display(rechazados.head())
    print(f"Shape: {rechazados.shape}")

    return rechazados


rejected_df = identificar_rechazo(cleaned_df)

Datos Rechazados con motivo:

Empty DataFrame
Columns: [id_aseguradora, nombre, pais, rating_riesgo, motivo_rechazo]
Index: []

Shape: (0, 5)

In [9]:
def exportar_datos(validos, rechazados):
    validos.to_csv("datos_validos.csv", index=False)
    rechazados.to_csv("datos_rechazados.csv", index=False)

    print("Archivos exportados correctamente:")
    print("- datos_validos.csv")
    print("- datos_rechazados.csv")


exportar_datos(valid_df, rejected_df)

Archivos exportados correctamente:
- datos_validos.csv
- datos_rechazados.csv

In [10]:

!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 36.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [11]:

from sqlalchemy import create_engine
import pandas as pd

In [12]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [13]:
engine = create_engine(database_url)

In [14]:
test = pd.read_sql("SELECT 1", engine)

In [15]:
print(test)

   ?column?
0         1

In [18]:
# 1. Subir las Aseguradoras Válidas
valid_df.to_sql(
    'datos_rechazados',
    engine,
    if_exists='replace',
    index=False
)

15

In [19]:
# 1. Subir las Aseguradoras Válidas
valid_df.to_sql(
    'datos_validos',
    engine,
    if_exists='replace',
    index=False
)

15

In [21]:
# Validar la carga de aseguradoras
pd.read_sql(
    "SELECT * FROM datos_validos LIMIT 10",
    engine
)

   id_aseguradora          nombre         pais rating_riesgo
0               1   Aseguradora 1   Costa Rica          Alto
1               2   Aseguradora 2  El Salvador          Bajo
2               3   Aseguradora 3  El Salvador           nan
3               4   Aseguradora 4   Costa Rica         Medio
4               5   Aseguradora 5  El Salvador          Bajo
5               6   Aseguradora 6          nan         Medio
6               7   Aseguradora 7    Guatemala          Alto
7               8   Aseguradora 8       Panamá          Bajo
8               9   Aseguradora 9          nan          Bajo
9              10  Aseguradora 10       Panamá           nan